trigger:
  branches:
    include:
    - develop
    - releases/*
  paths:
    exclude:
    - '**/*.md'
    - docs/*
pr:
  branches:
    include:
    - develop
    - releases/*
  paths:
    exclude:
    - '**/*.md'
    - docs/*

variables:
  DOTNET_NOLOGO: true
  NUGET_PACKAGES: '$(Pipeline.Workspace)/.nuget/packages'

pool:
  vmImage: windows-2022

steps:
- template: azure-pipelines-shared.yml

- script: dotnet tool restore
  displayName: Restore dotnet tools

- pwsh: dotnet cake --verbosity=Normal --target=Sonar --sonarKey=$env:SONARY_KEY
  env: 
    SONARY_KEY: $(sonarKey)